-keep class com.hss01248.appstartup.api.** { *; }
-keep class com.hss01248.startup.annotation.AppStartUpItem { *; }
-keep @com.hss01248.startup.annotation.AppStartUpItem class * {*;}
-keep class * implements com.hss01248.startup.annotation.AppStartUpItem